### ISSUE TITLE
Count3p.pl seems missing

### ISSUE THREAD

**Issue by ishaaq34** [michaelilab/TB_Pseudo_small_ncRNA#1]
Hi
Thank you for sharing the pipeline
While going through the RiboMethSeqPrepPipeline_rRNA.sh present in the unix script of Ribomethseq folder , I am not able to find the Count3p.pl  in the script folder 

Can you assist me in finding out the Count3p.pl. I would appreciate that much

Also , it would be helpful to me if you can let me know how did you generate the TB_rRNA_annot_Nm.txt file from rRNA fasta file

**Comment by michaelilab** [comment]
1) Apologies.  I have now added the  Count3p.pl file to the Scripts directory.
2) The TB_rRNA_annot_Nm.txt can be found in the DB directory

**Comment by ishaaq34** [comment]
Many thanks for sharing 
Actually - I have rRNA of c elegans . Is there any way , I can generate the annotation file like you have TB_rRNA_annot_Nm.txt for Trypanosoma rRNA ?

**Comment by michaelilab** [comment]
Do you have the list of locations of the known modifications? If you take the list from a database/publication - you must make sure your version of the rRNA that you are using corresponds to the same version reported in the paper. 
I created the file - with a combination of shell commands in UNIX and manual annotation. I will try to write a script to generate the same file - given an rRNA sequence, modification locations, and rRNA description file. I will update you - when it is available.

**Comment by michaelilab** [comment]
I created a script to create the annot file. See the scripts directory for the script and sample data to see how each input file should look.

**Comment by ishaaq34** [comment]
Thank so much that was helpful . I will do that .
 I  have been analyzing the data without the annotation file. Can you suggest me how can I proceed with the output file for rms score
<img width="581" alt="Screen Shot 2023-02-02 at 3 15 44 PM" src="https://user-images.githubusercontent.com/47107221/216451136-3547cd42-7835-4af2-aa45-ba9725ff35ce.png">
e.

**Comment by michaelilab** [comment]
Based on the publications of 
F. Pichot, V. Marchand, L. Ayadi, V. Bourguignon-Igel, M. Helm, Y. Motorin
Holistic Optimization of Bioinformatic Analysis Pipeline for Detection and Quantification of 2’-O-Methylations in RNA by RiboMethSeq  2020 
AND
Pichot et al. (https://www.sciencedirect.com/science/article/pii/S1046202322000743)


"Thus, in practice, the best compromise in detection of modified positions is defined as a combination of two thresholds (e.g. ScoreMean >0.92 and ScoreA >0.5)"


***It may be different in your data - take a look at how the known sites are detected.
